export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SIGN_IN_ENDED = 'SIGN_IN_ENDED';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const REMOVE_ARTIST = 'REMOVE_ARTIST';
export const STORE_ARTIST = 'STORE_ARTIST';
export const STORE_ARTISTS = 'STORE_ARTISTS';
export const ARTIST_STARTED_LOADING = 'ARTIST_STARTED_LOADING';
export const ARTIST_ENDED_LOADING = 'ARTIST_ENDED_LOADING';
export const ARTIST_ERROR = 'ARTIST_ERROR';
