export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SIGN_IN_ENDED = 'SIGN_IN_ENDED';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const REMOVE_ARTIST = 'REMOVE_ARTIST';
export const STORE_ARTIST = 'STORE_ARTIST';
export const STORE_ARTISTS = 'STORE_ARTISTS';
export const ARTIST_STARTED_LOADING = 'ARTIST_STARTED_LOADING';
export const ARTIST_ENDED_LOADING = 'ARTIST_ENDED_LOADING';

export const STORE_ORDERS = 'STORE_ORDERS';
export const POST_ORDER = 'POST_ORDER';
export const POST_ORDER_STARTED = 'POST_ORDER_STARTED';
export const POST_ORDER_ENDED = 'POST_ORDER_ENDED';
export const POST_ORDER_ERROR = 'POST_ORDER_ERROR';
export const LIST_ORDERS_STARTED = 'LIST_ORDERS_STARTED';
export const LIST_ORDER_SENDED = 'LIST_ORDER_SENDED';
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER';
export const DELAY_ORDER = 'DELAY_ORDER';
